package com.example.markdownreader.core.common

data class AppStrings(
    val appName: String,
    val settings: String,
    val back: String,
    val openFile: String,
    val createMarkdown: String,
    val importFile: String,
    val recentFiles: String,
    val categoriesPage: String,
    val sortByTime: String,
    val sortByName: String,
    val sortBySize: String,
    val favorite: String,
    val rename: String,
    val displayName: String,
    val search: String,
    val searchHint: String,
    val previous: String,
    val next: String,
    val noMatches: String,
    val importFolder: String,
    val scanningFolder: String,
    val importedCount: String,
    val share: String,
    val shareFile: String,
    val shareText: String,
    val shareRendered: String,
    val emptyLibrary: String,
    val libraryTagline: String,
    val librarySubtitle: String,
    val all: String,
    val uncategorized: String,
    val delete: String,
    val opened: String,
    val classifyDocument: String,
    val category: String,
    val save: String,
    val cancel: String,
    val reader: String,
    val reload: String,
    val edit: String,
    val about: String,
    val markdownEmpty: String,
    val editor: String,
    val saving: String,
    val saved: String,
    val markdown: String,
    val newMarkdownTitle: String,
    val language: String,
    val chinese: String,
    val english: String,
    val fontSize: String,
    val darkMode: String,
    val rememberRecent: String,
    val aboutApp: String,
    val aboutAppBody: String,
    val clearRecent: String,
    val clearRecentWarning: String,
    val clearRecentConfirmTitle: String,
    val clearRecentConfirmBody: String,
    val clear: String,
    val fileInfo: String,
    val fileName: String,
    val fileUri: String,
    val fileSize: String,
    val fileCategory: String,
    val lastOpened: String,
    val lastModified: String,
    val unknown: String,
)

fun stringsFor(languageCode: String): AppStrings =
    if (languageCode == "en") englishStrings else chineseStrings

private val chineseStrings = AppStrings(
    appName = "Vitamin",
    settings = "设置",
    back = "返回",
    openFile = "打开文件",
    createMarkdown = "新建 Markdown",
    importFile = "导入文件",
    recentFiles = "最近打开",
    categoriesPage = "分类",
    sortByTime = "按时间",
    sortByName = "按名称",
    sortBySize = "按大小",
    favorite = "收藏",
    rename = "重命名",
    displayName = "显示名称",
    search = "搜索",
    searchHint = "搜索当前文档",
    previous = "上一个",
    next = "下一个",
    noMatches = "无匹配",
    importFolder = "导入文件夹",
    scanningFolder = "正在扫描文件夹...",
    importedCount = "已导入 %d 个文件",
    share = "分享",
    shareFile = "分享文件",
    shareText = "分享文本",
    shareRendered = "分享渲染内容",
    emptyLibrary = "暂无 Markdown 文档",
    libraryTagline = "给 Markdown 补充灵感维生素",
    librarySubtitle = "打开、分类、阅读并编辑你的笔记。",
    all = "全部",
    uncategorized = "未分类",
    delete = "删除",
    opened = "打开时间",
    classifyDocument = "文档分类",
    category = "分类",
    save = "保存",
    cancel = "取消",
    reader = "阅读",
    reload = "重载",
    edit = "编辑",
    about = "关于",
    markdownEmpty = "Markdown 内容为空",
    editor = "编辑器",
    saving = "保存中",
    saved = "已保存",
    markdown = "Markdown",
    newMarkdownTitle = "未命名笔记.md",
    language = "界面语言",
    chinese = "中文",
    english = "English",
    fontSize = "字体大小",
    darkMode = "深色模式",
    rememberRecent = "记住最近打开文件",
    aboutApp = "关于 App",
    aboutAppBody = "Vitamin 是一个基于 Jetpack Compose、Markwon、Room 和 DataStore 的 Markdown 阅读与编辑 App。",
    clearRecent = "清空最近打开记录",
    clearRecentWarning = "此操作只清空记录，不会删除原文件。",
    clearRecentConfirmTitle = "确认清空？",
    clearRecentConfirmBody = "最近打开记录将被清空，但原始 Markdown 文件不会被删除。",
    clear = "清空",
    fileInfo = "文件信息",
    fileName = "文件名",
    fileUri = "文件位置",
    fileSize = "文件大小",
    fileCategory = "分类",
    lastOpened = "上次打开",
    lastModified = "修改时间",
    unknown = "未知",
)

private val englishStrings = AppStrings(
    appName = "Vitamin",
    settings = "Settings",
    back = "Back",
    openFile = "Open file",
    createMarkdown = "New Markdown",
    importFile = "Import file",
    recentFiles = "Recent",
    categoriesPage = "Categories",
    sortByTime = "Time",
    sortByName = "Name",
    sortBySize = "Size",
    favorite = "Favorite",
    rename = "Rename",
    displayName = "Display name",
    search = "Search",
    searchHint = "Search this document",
    previous = "Previous",
    next = "Next",
    noMatches = "No matches",
    importFolder = "Import folder",
    scanningFolder = "Scanning folder...",
    importedCount = "Imported %d files",
    share = "Share",
    shareFile = "Share file",
    shareText = "Share text",
    shareRendered = "Share rendered",
    emptyLibrary = "No Markdown documents yet",
    libraryTagline = "Fresh Markdown nutrition",
    librarySubtitle = "Open, classify, read, and edit your notes.",
    all = "All",
    uncategorized = "Uncategorized",
    delete = "Delete",
    opened = "Opened",
    classifyDocument = "Classify document",
    category = "Category",
    save = "Save",
    cancel = "Cancel",
    reader = "Reader",
    reload = "Reload",
    edit = "Edit",
    about = "About",
    markdownEmpty = "Markdown content is empty",
    editor = "Editor",
    saving = "Saving",
    saved = "Saved",
    markdown = "Markdown",
    newMarkdownTitle = "Untitled note.md",
    language = "Language",
    chinese = "Chinese",
    english = "English",
    fontSize = "Font size",
    darkMode = "Dark mode",
    rememberRecent = "Remember recent files",
    aboutApp = "About App",
    aboutAppBody = "Vitamin is a Markdown reader and editor powered by Jetpack Compose, Markwon, Room, and DataStore.",
    clearRecent = "Clear recent files",
    clearRecentWarning = "This only clears records. Original files are not deleted.",
    clearRecentConfirmTitle = "Clear recent files?",
    clearRecentConfirmBody = "Recent file records will be cleared, but your Markdown files will remain untouched.",
    clear = "Clear",
    fileInfo = "File information",
    fileName = "File name",
    fileUri = "File location",
    fileSize = "File size",
    fileCategory = "Category",
    lastOpened = "Last opened",
    lastModified = "Last modified",
    unknown = "Unknown",
)
